using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace DeadCodeEliminator;

/// <summary>
/// Generates a self-contained HTML report from scan results.
/// No external dependencies — all CSS and JS is inlined.
/// </summary>
public static class HtmlReporter
{
    public static void WriteReport(
        string outputPath,
        List<(string FilePath, ScanResult Result)> fileResults,
        string scannedPath,
        string version)
    {
        var sb = new StringBuilder();
        var allIssues = fileResults.SelectMany(f => f.Result.Issues).ToList();
        int totalFiles = fileResults.Count;
        int filesWithIssues = fileResults.Count(f => f.Result.Issues.Count > 0);
        int totalLines = fileResults.Sum(f => f.Result.TotalLines);
        int autoFix = allIssues.Count(i => !i.IsWarningOnly);
        int advisory = allIssues.Count(i => i.IsWarningOnly);
        string generatedAt = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"UTF-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"<title>Dead Code Report — {Path.GetFileName(scannedPath)}</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(GetCss());
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // ── Header ────────────────────────────────────────────────────────────
        sb.AppendLine("<div class=\"header\">");
        sb.AppendLine("  <div class=\"header-inner\">");
        sb.AppendLine($"  <h1>🧹 Dead Code Report</h1>");
        sb.AppendLine($"  <div class=\"meta\">Generated by deadcode v{version} &nbsp;·&nbsp; {generatedAt}</div>");
        sb.AppendLine($"  <div class=\"meta\">Scanned: <code>{HtmlEncode(scannedPath)}</code></div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</div>");

        // ── Summary cards ─────────────────────────────────────────────────────
        sb.AppendLine("<div class=\"summary\">");
        sb.AppendLine(StatCard("Files Scanned", totalFiles.ToString(), "card-neutral"));
        sb.AppendLine(StatCard("Files with Issues", filesWithIssues.ToString(), filesWithIssues > 0 ? "card-warn" : "card-ok"));
        sb.AppendLine(StatCard("Total Lines", totalLines.ToString(), "card-neutral"));
        sb.AppendLine(StatCard("Total Issues", allIssues.Count.ToString(), allIssues.Count > 0 ? "card-bad" : "card-ok"));
        sb.AppendLine(StatCard("Auto-Fixable", autoFix.ToString(), autoFix > 0 ? "card-fix" : "card-ok"));
        sb.AppendLine(StatCard("Advisory", advisory.ToString(), advisory > 0 ? "card-advisory" : "card-ok"));
        sb.AppendLine("</div>");

        // ── Category breakdown bar chart ──────────────────────────────────────
        var byKind = allIssues
            .GroupBy(i => i.Kind)
            .OrderByDescending(g => g.Count())
            .ToList();

        if (byKind.Count > 0)
        {
            sb.AppendLine("<div class=\"section\">");
            sb.AppendLine("<h2>Issues by Category</h2>");
            sb.AppendLine("<div class=\"chart\">");
            int maxCount = byKind.Max(g => g.Count());
            foreach (var group in byKind)
            {
                int count = group.Count();
                int pct = maxCount > 0 ? (int)((count / (double)maxCount) * 100) : 0;
                string kindClass = KindCssClass(group.Key);
                sb.AppendLine($"<div class=\"chart-row\">");
                sb.AppendLine($"  <div class=\"chart-label\">{KindLabel(group.Key)}</div>");
                sb.AppendLine($"  <div class=\"chart-bar-wrap\">");
                sb.AppendLine($"    <div class=\"chart-bar {kindClass}\" style=\"width:{pct}%\"></div>");
                sb.AppendLine($"    <span class=\"chart-count\">{count}</span>");
                sb.AppendLine($"  </div>");
                sb.AppendLine($"</div>");
            }
            sb.AppendLine("</div>");
            sb.AppendLine("</div>");
        }

        // ── Top offending files ────────────────────────────────────────────────
        var worst = fileResults
            .Where(f => f.Result.Issues.Count > 0)
            .OrderByDescending(f => f.Result.Issues.Count)
            .Take(10)
            .ToList();

        if (worst.Count > 0)
        {
            sb.AppendLine("<div class=\"section\">");
            sb.AppendLine("<h2>Top Files by Issue Count</h2>");
            sb.AppendLine("<div class=\"chart\">");
            int maxFileCount = worst.Max(f => f.Result.Issues.Count);
            foreach (var (filePath, fileResult) in worst)
            {
                string name = Path.GetFileName(filePath);
                string rel = Path.GetDirectoryName(filePath) ?? "";
                int count = fileResult.Issues.Count;
                int pct = maxFileCount > 0 ? (int)((count / (double)maxFileCount) * 100) : 0;
                sb.AppendLine($"<div class=\"chart-row\">");
                sb.AppendLine($"  <div class=\"chart-label\" title=\"{HtmlEncode(filePath)}\">{HtmlEncode(name)}<span class=\"chart-sublabel\">{HtmlEncode(rel)}</span></div>");
                sb.AppendLine($"  <div class=\"chart-bar-wrap\">");
                sb.AppendLine($"    <div class=\"chart-bar bar-file\" style=\"width:{pct}%\"></div>");
                sb.AppendLine($"    <span class=\"chart-count\">{count}</span>");
                sb.AppendLine($"  </div>");
                sb.AppendLine($"</div>");
            }
            sb.AppendLine("</div>");
            sb.AppendLine("</div>");
        }

        // ── Per-file results ──────────────────────────────────────────────────
        sb.AppendLine("<div class=\"section\">");
        sb.AppendLine("<div class=\"files-header\">");
        sb.AppendLine("<h2>File Details</h2>");
        sb.AppendLine("<div class=\"toggle-all\">");
        sb.AppendLine("<button onclick=\"expandAll()\">Expand All</button>");
        sb.AppendLine("<button onclick=\"collapseAll()\">Collapse All</button>");
        sb.AppendLine("</div>");
        sb.AppendLine("</div>");

        foreach (var (filePath, fileResult) in fileResults.OrderByDescending(f => f.Result.Issues.Count))
        {
            string relativePath = filePath;
            try { relativePath = Path.GetRelativePath(scannedPath, filePath); } catch { }

            bool hasIssues = fileResult.Issues.Count > 0;
            string fileId = $"file_{Math.Abs(filePath.GetHashCode())}";
            string statusClass = hasIssues ? "file-has-issues" : "file-clean";
            string icon = hasIssues ? "⚠" : "✓";

            sb.AppendLine($"<div class=\"file-block {statusClass}\">");
            sb.AppendLine($"  <div class=\"file-title\" onclick=\"toggleFile('{fileId}')\">");
            sb.AppendLine($"    <span class=\"file-icon\">{icon}</span>");
            sb.AppendLine($"    <span class=\"file-name\">{HtmlEncode(relativePath)}</span>");
            if (hasIssues)
            {
                sb.AppendLine($"    <span class=\"file-badge\">{fileResult.Issues.Count} issue{(fileResult.Issues.Count != 1 ? "s" : "")}</span>");
                int fileAutoFix = fileResult.Issues.Count(i => !i.IsWarningOnly);
                int fileAdvisory = fileResult.Issues.Count(i => i.IsWarningOnly);
                if (fileAutoFix > 0)
                    sb.AppendLine($"    <span class=\"badge-fix\">{fileAutoFix} auto-fix</span>");
                if (fileAdvisory > 0)
                    sb.AppendLine($"    <span class=\"badge-advisory\">{fileAdvisory} advisory</span>");
            }
            else
            {
                sb.AppendLine($"    <span class=\"file-clean-label\">Clean</span>");
            }
            sb.AppendLine($"    <span class=\"file-lines\">{fileResult.TotalLines} lines</span>");
            sb.AppendLine($"    <span class=\"collapse-icon\" id=\"icon_{fileId}\">▼</span>");
            sb.AppendLine($"  </div>");

            sb.AppendLine($"  <div class=\"file-body\" id=\"{fileId}\">");

            if (!hasIssues)
            {
                sb.AppendLine("    <div class=\"no-issues\">✓ No dead code found in this file.</div>");
            }
            else
            {
                // Group by kind
                var grouped = fileResult.Issues
                    .GroupBy(i => i.Kind)
                    .OrderBy(g => g.Key.ToString());

                foreach (var group in grouped)
                {
                    sb.AppendLine($"    <div class=\"issue-group\">");
                    sb.AppendLine($"      <div class=\"issue-group-title\">{KindLabel(group.Key)} <span class=\"issue-group-count\">{group.Count()}</span></div>");
                    sb.AppendLine($"      <table class=\"issue-table\">");
                    sb.AppendLine($"        <thead><tr><th>Line</th><th>Description</th><th>Action</th><th>Code</th></tr></thead>");
                    sb.AppendLine($"        <tbody>");

                    foreach (var issue in group)
                    {
                        string lineRef = issue.LineStart == issue.LineEnd
                            ? $"{issue.LineStart}"
                            : $"{issue.LineStart}–{issue.LineEnd}";
                        string actionClass = issue.IsWarningOnly ? "action-advisory" : "action-fix";
                        string actionLabel = issue.IsWarningOnly ? "Advisory" : "Auto-fix";
                        string rowClass = issue.IsWarningOnly ? "row-advisory" : "row-fix";

                        sb.AppendLine($"          <tr class=\"{rowClass}\">");
                        sb.AppendLine($"            <td class=\"col-line\">{lineRef}</td>");
                        sb.AppendLine($"            <td class=\"col-desc\">{HtmlEncode(issue.Description)}</td>");
                        sb.AppendLine($"            <td><span class=\"action-badge {actionClass}\">{actionLabel}</span></td>");
                        sb.AppendLine($"            <td class=\"col-code\">");
                        if (issue.Context.Count > 0)
                        {
                            sb.AppendLine($"              <div class=\"code-block\">");
                            foreach (var ctx in issue.Context)
                            {
                                string lineClass = ctx.IsHighlighted ? "code-line highlighted" : "code-line";
                                string marker = ctx.IsHighlighted ? "▶" : " ";
                                sb.AppendLine($"                <div class=\"{lineClass}\">");
                                sb.AppendLine($"                  <span class=\"code-gutter\">{marker}{ctx.LineNumber}</span>");
                                sb.AppendLine($"                  <span class=\"code-text\">{HtmlEncode(ctx.Content)}</span>");
                                sb.AppendLine($"                </div>");
                            }
                            sb.AppendLine($"              </div>");
                        }
                        else if (!string.IsNullOrWhiteSpace(issue.LineContent))
                        {
                            sb.AppendLine($"              <code>{HtmlEncode(issue.LineContent)}</code>");
                        }
                        sb.AppendLine($"            </td>");
                        sb.AppendLine($"          </tr>");
                    }

                    sb.AppendLine($"        </tbody>");
                    sb.AppendLine($"      </table>");
                    sb.AppendLine($"    </div>");
                }
            }

            sb.AppendLine("  </div>"); // file-body
            sb.AppendLine("</div>"); // file-block
        }

        sb.AppendLine("</div>"); // section

        // ── Footer ────────────────────────────────────────────────────────────
        sb.AppendLine("<div class=\"footer\">");
        sb.AppendLine($"  deadcode v{version} &nbsp;·&nbsp; {generatedAt}");
        sb.AppendLine("</div>");

        sb.AppendLine("<script>");
        sb.AppendLine(GetJs());
        sb.AppendLine("</script>");

        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    // ── Convenience overload for single file ──────────────────────────────────

    public static void WriteReport(
        string outputPath,
        string filePath,
        ScanResult result,
        string version)
    {
        WriteReport(
            outputPath,
            new List<(string, ScanResult)> { (filePath, result) },
            filePath,
            version);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string StatCard(string label, string value, string cssClass)
    {
        return $"<div class=\"card {cssClass}\"><div class=\"card-value\">{value}</div><div class=\"card-label\">{label}</div></div>";
    }

    private static string KindLabel(IssueKind kind) => kind switch
    {
        IssueKind.UnusedUsing => "Unused Using Directives",
        IssueKind.UnreachableCode => "Unreachable Code",
        IssueKind.UnusedVariable => "Unused Local Variables",
        IssueKind.CommentedCode => "Commented-Out Code",
        IssueKind.UnusedPrivateMethod => "Unused Private Methods",
        IssueKind.UnusedPrivateField => "Unused Private Fields",
        IssueKind.EmptyBlock => "Empty Blocks",
        IssueKind.DeadConditional => "Dead Conditionals",
        IssueKind.RedundantAssignment => "Redundant Assignments",
        _ => kind.ToString()
    };

    private static string KindCssClass(IssueKind kind) => kind switch
    {
        IssueKind.UnreachableCode => "bar-red",
        IssueKind.DeadConditional => "bar-red",
        IssueKind.UnusedUsing => "bar-blue",
        IssueKind.UnusedVariable => "bar-orange",
        IssueKind.UnusedPrivateMethod => "bar-purple",
        IssueKind.UnusedPrivateField => "bar-purple",
        IssueKind.CommentedCode => "bar-gray",
        IssueKind.RedundantAssignment => "bar-orange",
        IssueKind.EmptyBlock => "bar-gray",
        _ => "bar-blue"
    };

    private static string HtmlEncode(string text) =>
        text.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");

    // ── CSS ───────────────────────────────────────────────────────────────────

    private static string GetCss() => """
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #0f1117;
            color: #e2e8f0;
            font-size: 14px;
            line-height: 1.6;
        }

        .header {
            background: linear-gradient(135deg, #1a1f2e 0%, #0f1117 100%);
            border-bottom: 1px solid #2d3748;
            padding: 32px 0 24px;
        }
        .header-inner { max-width: 1100px; margin: 0 auto; padding: 0 24px; }
        .header h1 { font-size: 28px; font-weight: 700; color: #fff; margin-bottom: 8px; }
        .meta { color: #718096; font-size: 13px; margin-top: 4px; }
        .meta code { background: #2d3748; padding: 2px 6px; border-radius: 4px; font-size: 12px; color: #a0aec0; }

        .summary {
            display: flex;
            gap: 16px;
            flex-wrap: wrap;
            max-width: 1100px;
            margin: 24px auto;
            padding: 0 24px;
        }

        .card {
            flex: 1;
            min-width: 130px;
            background: #1a1f2e;
            border: 1px solid #2d3748;
            border-radius: 10px;
            padding: 16px;
            text-align: center;
        }
        .card-value { font-size: 32px; font-weight: 700; margin-bottom: 4px; }
        .card-label { font-size: 11px; color: #718096; text-transform: uppercase; letter-spacing: 0.05em; }
        .card-neutral .card-value { color: #a0aec0; }
        .card-ok .card-value { color: #48bb78; }
        .card-warn .card-value { color: #ed8936; }
        .card-bad .card-value { color: #fc8181; }
        .card-fix .card-value { color: #63b3ed; }
        .card-advisory .card-value { color: #f6e05e; }

        .section {
            max-width: 1100px;
            margin: 0 auto 32px;
            padding: 0 24px;
        }
        .section h2 {
            font-size: 16px;
            font-weight: 600;
            color: #a0aec0;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            margin-bottom: 16px;
            padding-bottom: 8px;
            border-bottom: 1px solid #2d3748;
        }

        .chart { display: flex; flex-direction: column; gap: 10px; }
        .chart-row { display: flex; align-items: center; gap: 12px; }
        .chart-label {
            width: 220px;
            flex-shrink: 0;
            font-size: 13px;
            color: #cbd5e0;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .chart-sublabel { display: block; font-size: 11px; color: #4a5568; }
        .chart-bar-wrap { flex: 1; display: flex; align-items: center; gap: 8px; }
        .chart-bar {
            height: 20px;
            border-radius: 4px;
            min-width: 4px;
            transition: width 0.3s ease;
        }
        .chart-count { font-size: 13px; color: #718096; min-width: 28px; }
        .bar-red    { background: #fc8181; }
        .bar-blue   { background: #63b3ed; }
        .bar-orange { background: #ed8936; }
        .bar-purple { background: #b794f4; }
        .bar-gray   { background: #718096; }
        .bar-file   { background: #4299e1; }

        .files-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #2d3748; }
        .files-header h2 { margin-bottom: 0; padding-bottom: 0; border-bottom: none; }
        .toggle-all { display: flex; gap: 8px; }
        .toggle-all button {
            background: #2d3748;
            color: #a0aec0;
            border: 1px solid #4a5568;
            border-radius: 6px;
            padding: 4px 12px;
            font-size: 12px;
            cursor: pointer;
        }
        .toggle-all button:hover { background: #4a5568; }

        .file-block {
            background: #1a1f2e;
            border: 1px solid #2d3748;
            border-radius: 10px;
            margin-bottom: 12px;
            overflow: hidden;
        }
        .file-block.file-clean { border-color: #2f4a38; }
        .file-block.file-has-issues { border-color: #4a3728; }

        .file-title {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 14px 18px;
            cursor: pointer;
            user-select: none;
            flex-wrap: wrap;
        }
        .file-title:hover { background: #212636; }
        .file-icon { font-size: 14px; flex-shrink: 0; }
        .file-clean .file-icon { color: #48bb78; }
        .file-has-issues .file-icon { color: #ed8936; }
        .file-name { font-family: 'Consolas', 'Courier New', monospace; font-size: 13px; color: #e2e8f0; flex: 1; }
        .file-badge { background: #744210; color: #fbd38d; font-size: 11px; padding: 2px 8px; border-radius: 12px; }
        .badge-fix { background: #1a365d; color: #63b3ed; font-size: 11px; padding: 2px 8px; border-radius: 12px; }
        .badge-advisory { background: #5f370e; color: #f6e05e; font-size: 11px; padding: 2px 8px; border-radius: 12px; }
        .file-clean-label { color: #48bb78; font-size: 12px; }
        .file-lines { color: #4a5568; font-size: 11px; margin-left: auto; }
        .collapse-icon { color: #4a5568; font-size: 11px; flex-shrink: 0; transition: transform 0.2s; }
        .collapse-icon.collapsed { transform: rotate(-90deg); }

        .file-body { padding: 0 18px 18px; }
        .file-body.hidden { display: none; }

        .no-issues { color: #48bb78; font-size: 13px; padding: 8px 0; }

        .issue-group { margin-bottom: 20px; }
        .issue-group-title {
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            color: #718096;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            gap: 8px;
        }
        .issue-group-count {
            background: #2d3748;
            color: #a0aec0;
            font-size: 11px;
            padding: 1px 7px;
            border-radius: 10px;
        }

        .issue-table { width: 100%; border-collapse: collapse; font-size: 13px; }
        .issue-table thead th {
            text-align: left;
            padding: 6px 10px;
            font-size: 11px;
            color: #4a5568;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            border-bottom: 1px solid #2d3748;
        }
        .issue-table tbody tr { border-bottom: 1px solid #1e2433; }
        .issue-table tbody tr:last-child { border-bottom: none; }
        .issue-table tbody tr:hover { background: #212636; }
        .row-fix td { border-left: 2px solid #63b3ed; padding-left: 8px; }
        .row-advisory td { border-left: 2px solid #f6e05e; padding-left: 8px; }
        .issue-table td { padding: 7px 10px; vertical-align: top; }
        .col-line { color: #718096; font-family: monospace; white-space: nowrap; width: 60px; }
        .col-desc { color: #cbd5e0; }
        .col-code { width: 35%; }
        .col-code code {
            display: block;
            background: #0d1117;
            border: 1px solid #2d3748;
            border-radius: 4px;
            padding: 4px 8px;
            font-family: 'Consolas', 'Courier New', monospace;
            font-size: 12px;
            color: #a0aec0;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 360px;
        }

        .action-badge { font-size: 11px; padding: 2px 8px; border-radius: 10px; white-space: nowrap; }
        .action-fix { background: #1a365d; color: #63b3ed; }
        .action-advisory { background: #5f370e; color: #f6e05e; }

        .code-block {
            background: #0d1117;
            border: 1px solid #2d3748;
            border-radius: 6px;
            overflow: hidden;
            font-family: 'Consolas', 'Courier New', monospace;
            font-size: 12px;
        }
        .code-line {
            display: flex;
            align-items: stretch;
            border-bottom: 1px solid #161b22;
        }
        .code-line:last-child { border-bottom: none; }
        .code-line.highlighted { background: #2d1f0a; border-left: 3px solid #ed8936; }
        .code-gutter {
            min-width: 48px;
            padding: 3px 8px;
            color: #4a5568;
            background: #0a0d13;
            text-align: right;
            user-select: none;
            flex-shrink: 0;
            font-size: 11px;
        }
        .code-line.highlighted .code-gutter { color: #ed8936; background: #1a1205; }
        .code-text {
            padding: 3px 10px;
            color: #a0aec0;
            white-space: pre;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .code-line.highlighted .code-text { color: #fbd38d; }

        .footer {
            text-align: center;
            padding: 24px;
            color: #4a5568;
            font-size: 12px;
            border-top: 1px solid #2d3748;
            margin-top: 32px;
        }
    """;

    // ── JavaScript ────────────────────────────────────────────────────────────

    private static string GetJs() => """
        function toggleFile(id) {
            const body = document.getElementById(id);
            const icon = document.getElementById('icon_' + id);
            if (!body) return;
            body.classList.toggle('hidden');
            icon.classList.toggle('collapsed');
        }

        function expandAll() {
            document.querySelectorAll('.file-body').forEach(el => el.classList.remove('hidden'));
            document.querySelectorAll('.collapse-icon').forEach(el => el.classList.remove('collapsed'));
        }

        function collapseAll() {
            document.querySelectorAll('.file-body').forEach(el => el.classList.add('hidden'));
            document.querySelectorAll('.collapse-icon').forEach(el => el.classList.add('collapsed'));
        }

        // Start with files-with-issues expanded, clean files collapsed
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('.file-block.file-clean .file-body').forEach(el => {
                el.classList.add('hidden');
                const id = el.id;
                const icon = document.getElementById('icon_' + id);
                if (icon) icon.classList.add('collapsed');
            });
        });
    """;
}